services:
  backend:
    image: thai03/monitoreo_pis6to-backend:latest
    container_name: monitoreo_pis_backend
    ports:
      - "3000:3000"  # Exponer el puerto 3000 del contenedor en el puerto 3000 del host
    networks:
      - monitoreo_network

  frontend:
    image: thai03/monitoreo_pis6to-frontend:latest
    container_name: monitoreo_pis_frontend
    ports:
      - "3001:3000"  # Exponer el puerto 3000 del contenedor en el puerto 3001 del host
    depends_on:
      - backend
    networks:
      - monitoreo_network

networks:
  monitoreo_network:
    driver: bridge
